---
system:
  runWithDefault:
    posixUser: bin
    posixGroup: bin

services:
  main:
    dependencies:
      - echo_service
    lifecycle:
      posix:
        run:
          echo "Running main"
  echo_service:
    lifecycle:
      install:
        posix: echo "install as `id -u`"
      run:
        posix:
          requiresPrivilege: true
          script: echo "run as `id -u`"
    version: 1.0.0
