services:
  aws.greengrass.Nucleus:
    parameters:
      runWithDefault:
        posixUser: nobody

  installerror:
    lifecycle:
      posix:
        install: |-
          echo "INSTALL_ERROR"
          exit 1
      windows:
        install: |-
          powershell -command echo INSTALL_ERROR; exit 1

  main:
    lifecycle:
      install:
        all: echo All installed
      posix:
        run: |-
          echo main of config_install_error is running
          while true; do
          date; sleep 5;
          done
      windows:
        run: >-
          powershell -command "& { echo \"main of config_install_error is running\"; while (1) { sleep 5 } }"
    dependencies:
      - installerror
