---
services:
  aws.greengrass.Nucleus:
    parameters:
      runWithDefault:
        posixUser: nobody

  main:
    dependencies:
      - echo_service
    lifecycle:
      posix:
        run:
          echo "Running main"
  echo_service:
    lifecycle:
      install:
        posix: echo "install as `id -u -n`"
      run:
        posix: echo "run as `id -u -n`"
    version: 1.0.0
