services:
  aws.greengrass.Nucleus:
    configuration:
      runWithDefault:
        posixUser: nobody
        windowsUser: integ-tester

  installerror:
    lifecycle:
      posix:
        install: |-
          echo "INSTALL_ERROR"
          exit 1
      windows:
        install: echo INSTALL_ERROR && exit /b 1

  main:
    lifecycle:
      install:
        all: echo All installed
      posix:
        run: |-
          echo main of config_install_error is running
          while true; do
          date; sleep 5;
          done
      windows:
        run: echo main of config_install_error is running && ping -n 1000 127.0.0.1 > NUL
    dependencies:
      - installerror
