services:
  aws.greengrass.Nucleus:
    configuration:
      runWithDefault:
        posixUser: nobody
        windowsUser: integ-tester

  installerror:
    lifecycle:
      posix:
        install: |-
          sleep 2
          echo "INSTALL_SUCCESS"
          exit 0
      windows:
        install: >-
          powershell -command sleep 2; echo INSTALL_SUCCESS; exit 0
  main:
    lifecycle:
      install:
        all: echo All installed
      posix:
        run: |-
          echo main of config_install_succeed_partial is running
          while true; do
          date; sleep 5;
          done
      windows:
        run: >-
          powershell -command "& { echo \"main of config_install_succeed_partial is running\"; while(1) { sleep 5 } }"
    dependencies:
      - installerror
