services:
  aws.greengrass.Nucleus:
    parameters:
      runWithDefault:
        posixUser: nobody

  simpleRun:
    lifecycle:
      run: |-
        sleep 2
        echo "RUN_SUCCESS"
        exit 0
