---
services:
  aws.greengrass.Nucleus:
    parameters:
      runWithDefault:
        posixUser: nobody

  main:
    lifecycle:
      install:
        all: echo All installed
  TelemetryAgent:
    parameters:
      periodicAggregateMetricsIntervalSec: 2
      periodicPublishMetricsIntervalSec: 4
