---
services:
  aws.greengrass.Nucleus:
    configuration:
      runWithDefault:
        posixUser: nobody
        windowsUser: integ-tester

  main:
    lifecycle:
      install:
        all: echo All installed
