---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.iot.gg.test.integ.SystemConfigTest
ComponentDescription: This is a main that depends on aws.iot.gg.test.integ.ComponentConfigTestService-1.0.0.yaml
ComponentPublisher: Me
ComponentVersion: '0.0.1'

ComponentDependencies:
  GreenSignal:
    VersionRequirement: 1.0.0

Manifests:
  - Platform:
      os: all
    Lifecycle:
      ## Texts below are used for assertion in DeploymentTaskIntegrationTest and need to be changed together.
      run: >-
        echo "aws.iot.gg.test.integ.SystemConfigTest output
        I'm kernel's root path: {kernel:rootPath} to assert.
        I'm my own artifact path: {artifacts:path} to assert.
        I'm my own artifact decompressed path: {artifacts:decompressedPath} to assert.
        I'm GreenSignal's artifact path: {GreenSignal:artifacts:path} to assert.
        I'm GreenSignal's artifact decompressed path: {GreenSignal:artifacts:decompressedPath} to assert.
        "