---
services:
  aws.greengrass.Nucleus:
    parameters:
      runWithDefault:
        posixUser: nobody
  bar:
    lifecycle:
      run: echo bar-service phase 3
  main:
    lifecycle:
      install:
        all: echo All installed
    dependencies:
      - bar
      - aws.greengrass.Nucleus
