#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.Nucleus
ComponentType: aws.greengrass.nucleus
ComponentDescription: Core functionality for device side orchestration of deployments and lifecycle management for execution of Greengrass components and applications. This includes features such as starting, stopping, and monitoring execution of components and apps, inter-process communication server for communication between components, component installation and configuration management. This is a fundamental cornerstone of open-sourcing Greengrass, providing documentation and ability to debug Greengrass Core.
ComponentPublisher: AWS
ComponentVersion: '2.13.0'
ComponentConfiguration:
  DefaultConfiguration:
    iotDataEndpoint: ""
    iotCredEndpoint: ""
    greengrassDataPlanePort: 8443
    awsRegion: ""
    iotRoleAlias: ""
    mqtt: {}
    networkProxy: {}
    runWithDefault: {}
    deploymentPollingFrequencySeconds: 15
    componentStoreMaxSizeBytes: 10000000000
    platformOverride: {}
Manifests:
  - Platform:
      os: darwin
    Lifecycle:
      bootstrap:
        RequiresPrivilege: true
        script: |-

          set -eu
          KERNEL_ROOT="{kernel:rootPath}"
          UNPACK_DIR="{artifacts:decompressedPath}/aws.greengrass.nucleus"
          rm -r "$KERNEL_ROOT"/alts/current/*
          echo "{configuration:/jvmOptions}" > "$KERNEL_ROOT/alts/current/launch.params"
          ln -sf "$UNPACK_DIR" "$KERNEL_ROOT/alts/current/distro"
          exit 100

  - Platform:
      os: linux
    Lifecycle:
      bootstrap:
        RequiresPrivilege: true
        script: |-

          set -eu
          KERNEL_ROOT="{kernel:rootPath}"
          UNPACK_DIR="{artifacts:decompressedPath}/aws.greengrass.nucleus"
          rm -r "$KERNEL_ROOT"/alts/current/*
          echo "{configuration:/jvmOptions}" > "$KERNEL_ROOT/alts/current/launch.params"
          ln -sf "$UNPACK_DIR" "$KERNEL_ROOT/alts/current/distro"
          exit 100
  - Platform:
      os: windows
    Lifecycle:
      bootstrap:
        RequiresPrivilege: true
        script: >-
          copy "{kernel:rootPath}\alts\current\distro\bin\greengrass.xml" "{artifacts:decompressedPath}\aws.greengrass.nucleus\bin\greengrass.xml"& del /q "{kernel:rootPath}\alts\current\*"&& for /d %x in ("{kernel:rootPath}\alts\current\*") do @rd /s /q "%x"&& echo {configuration:/jvmOptions} > "{kernel:rootPath}\alts\current\launch.params"&& mklink /d "{kernel:rootPath}\alts\current\distro" "{artifacts:decompressedPath}\aws.greengrass.nucleus"&& exit 100
