---
RecipeTemplateVersion: '2020-01-25'
PackageName: KernelIntegTestDependency
Description: Test recipe for Evergreen packages
Publisher: Me
Version: '1.0.0'
Lifecycle:
  install:
    all:
      skipif: onpath git
      script: sudo apt-get install git
    debian:
      skipif: onpath git
      script: sudo apt-get install git
    macos:
      skipif: onpath git
      script: brew install git
Dependencies:
  all:
    Log:
      VersionRequirements: '2.0'
      DependencyType: Soft
    Cool-Database:
      VersionRequirements: '1.0'
      DependencyType: Hard
