services:
  installErrorRetry:
    lifecycle:
      install: |-
        sleep 1
        if [ -f "/tmp/egInstallErrorRetry" ]; then
          echo "INSTALL_SUCCEED"
          rm /tmp/egInstallErrorRetry
        else
          echo "INSTALL_FAIL"
          touch /tmp/egInstallErrorRetry
          exit 1
        fi
      shutdown:
        rm -f /tmp/egInstallErrorRetry

  runErrorRetry:
    lifecycle:
      run: |-
        sleep 5
        echo "RUN_BROKEN"
        exit 1

  main:
    lifecycle:
      install:
        all: echo All installed
      run: |-
        echo main of config_broken is running
        while true; do
        date; sleep 5;
        done
    dependencies:
      - installErrorRetry
      - runErrorRetry
