---
RecipeTemplateVersion: '2020-01-25'
PackageName: CustomerApp
Description: A customer app
Publisher: Me
Version: '0.9.0'

Lifecycle:
  startup: |-
    sleep 2
    echo "CustomerApp encounters error."
    exit 1
Dependencies:
  Mosquitto: 1.0.0
