---
RecipeTemplateVersion: '2020-01-25'
PackageName: KernelIntegTest
Description: Test recipe for Evergreen packages
Publisher: Me
Version: '1.0.0'
Lifecycle:
  install:
    all:
      skipif: onpath git
      script: sudo apt-get install git
    debian:
      skipif: onpath git
      script: sudo apt-get install git
    macos:
      skipif: onpath git
      script: brew install git
Artifacts:
  all:
    - greengrass:kernel_integ_test_artifact.txt
Dependencies:
  all:
    Log:
      VersionRequirements: '>1.0'
      DependencyType: Soft
    KernelIntegTestDependency:
      VersionRequirements: '1.0.0'
      DependencyType: Hard
