#!/bin/sh -x

PWD=$(dirname "$0")

# Assuming loader is launched from "$GG_ROOT/alts/current/distro/bin/loader"
GG_ROOT=$(cd $PWD/../../../..; pwd)

echo "Greengrass root: "${GG_ROOT}

LAUNCH_DIR="$GG_ROOT/alts/current"
CONFIG_FILE=""

is_directory_link() {
  [ -L "$1" ] && [ -d "$1" ]
}

launch_kernel() {
  if ! is_directory_link "${LAUNCH_DIR}"; then
    echo FATAL: No Kernel found!
    exit 1
  fi

  if [ -f "${LAUNCH_DIR}/launch.params" ] ; then
    JVM_OPTIONS=$(cat "$LAUNCH_DIR/launch.params")
  fi

  JVM_OPTIONS="$JVM_OPTIONS -Droot=$GG_ROOT"
  OPTIONS="--setup-system-service false"
  if [ ! -z ${CONFIG_FILE} ]; then
    OPTIONS="$OPTIONS --config $CONFIG_FILE"
  fi
  echo "jvm options: "${JVM_OPTIONS}
  echo "kernel options: "${OPTIONS}
  java ${JVM_OPTIONS} -Dlog.store=FILE -Dlog.fmt=JSON -jar "$LAUNCH_DIR/distro/lib/Greengrass.jar" ${OPTIONS}
  kernel_exit_code=$?
  echo "kernel exit at code: "${kernel_exit_code}
}

flip_link() {
  rm $2 || true
  ln -s $(readlink $1) $2
  rm $1 || true
}

# Determine Kernel stage and proper config files based on launch directory
if is_directory_link "${GG_ROOT}/alts/new"; then
  if ! is_directory_link "${GG_ROOT}/alts/old" && is_directory_link "${LAUNCH_DIR}"; then
    flip_link "${LAUNCH_DIR}" "${GG_ROOT}/alts/old"
  fi
  flip_link "${GG_ROOT}/alts/new" "${LAUNCH_DIR}"
fi

if is_directory_link "${GG_ROOT}/alts/broken" && is_directory_link "${GG_ROOT}/alts/old"; then
  flip_link "${GG_ROOT}/alts/old" "${LAUNCH_DIR}"
fi

if is_directory_link "${GG_ROOT}/alts/old" && ! is_directory_link "${LAUNCH_DIR}"; then
  flip_link "${GG_ROOT}/alts/old" "${LAUNCH_DIR}"
fi

# Launch Kernel with max 3 retries
j=1
while [ $j -le 3 ]; do
  launch_kernel
  case ${kernel_exit_code} in
  100|0)
    echo "Restarting kernel"
    # Exec loader from the same path, but the script might have changed due to kernel update
    exec "${LAUNCH_DIR}/distro/bin/loader"
    ;;
  101)
    echo "Rebooting host"
    sudo reboot
    ;;
  *)
    echo "Kernel exit ${kernel_exit_code}. Retrying $j times"
    ;;
  esac
  j=$(( j + 1 ))
done

# when reaching here, kernel has restarted 3 times and fails. Keep the current status and flip symlink.
if is_directory_link "${GG_ROOT}/alts/old" && is_directory_link "${LAUNCH_DIR}"; then
  flip_link "${LAUNCH_DIR}" "${GG_ROOT}/alts/broken"
  flip_link "${GG_ROOT}/alts/old" "${LAUNCH_DIR}"
fi

exit ${kernel_exit_code}
