---
services:
  git:
    lifecycle:
      install:
        debian:
          skipif: onpath git
          script: sudo apt-get install git
        macos:
          skipif: onpath git
          script: brew install git
    dependencies:
      macos:
        - homebrew
  homebrew:
    lifecycle:
      install:
        macos:
          skipif: onpath brew
          script: /usr/bin/ruby -e "$(curl --silent -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  docker:
    lifecycle:
      startup:
        macos: open /Applications/Docker.app
      install:
        skipif: onpath docker
        debian: |-
          curl --silent -sSL https://get.docker.com/ | sh
        fedora: sudo dnf install docker
        macos:
          skipif: exists /Applications/Docker.app
          script: |-
            find $(brew --cache)/downloads/ -name *Docker.dmg.incomplete | xargs rm -f
            brew cask install docker
    dependencies:
      macos:
        - homebrew

  hello-docker:
    dependencies:
      - docker
    lifecycle:
      run: docker run --rm hello-world
      shutdown: (docker stop hello-world; docker rm hello-world; exit 0)2>&1

  broken:
    lifecycle:
      startup: exit -1
  ticktock:
    lifecycle:
      run: echo tick-tock
    periodic: 1 seconds
  setenv:
    ANSWER: 42
  main:
    lifecycle:
      install:
        all: echo All installed
      posix:
        run: |-
          echo $PATH
          pwd
          printenv
          while true; do
          date; sleep 5; echo MAIN IS RUNNING
          done
      windows:
        run: >-
          powershell -command "& { while(1) {echo ANSWER=$env:ANSWER; echo EVERGREEN_UID=$env:EVERGREEN_UID;
          echo JUSTME=$env:JUSTME; sleep 5; echo \"MAIN IS RUNNING\"; } }"
    dependencies:
      macos:
        - git
        - hello-docker
        - ticktock:SOFT
      all:
        - ticktock:SOFT
      linux:
        - git
        - ticktock:SOFT # Remove docker dependency for github code check run due to docker install failure.
    setenv:
      JUSTME: fancy a spot of tea?
