---
services:
  git:
    lifecycle:
      install:
        debian:
          skipif: onpath git
          script: sudo apt-get install git
        macos:
          skipif: onpath git
          script: brew install git
    dependencies:
      macos:
        - homebrew
  homebrew:
    lifecycle:
      install:
        macos:
          skipif: onpath brew
          script: /usr/bin/ruby -e "$(curl --silent -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  docker:
    bashtimeout: 300
    lifecycle:
      startup:
        macos: open /Applications/Docker.app
      install:
        skipif: onpath docker
        debian: |-
          curl --silent -sSL https://get.docker.com/ | sh
        fedora: sudo dnf install docker
        macos:
          skipif: exists /Applications/Docker.app
          script: |-
            find $(brew --cache)/downloads/ -name *Docker.dmg.incomplete | xargs rm -f
            brew cask install docker
    dependencies:
      macos:
        - homebrew

  hello-docker:
    dependencies:
      - docker
    lifecycle:
      run: docker run --rm hello-world
      shutdown: (docker stop hello-world; docker rm hello-world; exit 0)2>&1
  hello-docker-nginx:
    lifecycle:
      run:  (docker run -d nginx; docker logs -f nginx; exit 0)2>&1
      shutdown: (docker stop nginx; docker rm nginx; exit 0)2>&1
    dependencies:
      - docker

  fallbackMain:  # This service only gets invoked if the main service fails to even begin to boot
    lifecycle:
      startup: echo sudo reboot -force   # TODO: this is stupid.  Should try to talk to cloud
  broken:
    lifecycle:
      startup: exit -1
  ticktock:
    lifecycle:
      run: echo tick-tock
    periodic: 2 seconds
  setenv:
    ANSWER: 42
  main:
    lifecycle:
      install:
        all: echo All installed
      run: |-
        echo $PATH
        pwd
        printenv
        while true; do
        date; sleep 5; echo MAIN IS RUNNING
        done
      download:
        hw.jar: http://foo/hw.jar
    dependencies:
      macos:
        - git
        - hello-docker
        - hello-docker-nginx
        - ticktock:INSTALLED
      linux:
        - git
        - ticktock:INSTALLED # Remove docker dependency for github code check run due to docker install failure.
    setenv:
      JUSTME: fancy a spot of tea?
    args: -jar {hw.jar}
