services:
  startupError:
    lifecycle:
      startup: |-
        echo "STARTUP_ERROR"
        exit 1

  main:
    lifecycle:
      install:
        all: echo All installed
      run: |-
        echo main of config_startup_error is running
        while true; do
        date; sleep 5;
        done
    dependencies:
      - startupError
