services:
  installerror:
    lifecycle:
      install: |-
        sleep 2
        echo "INSTALL_SUCCESS"
        exit 0
  main:
    lifecycle:
      install:
        all: echo All installed
      run: |-
        echo main of config_install_succeed_partial is running
        while true; do
        date; sleep 5;
        done
    dependencies:
      - installerror
