services:
  startupErrorRetry:
    lifecycle:
      startup: |-
        sleep 1
        if [ -f "/tmp/egStartupErrorRetrySucceed" ]; then
          echo "StartUp_SUCCEED"
          rm /tmp/egStartupErrorRetrySucceed
        else
          echo "StartUp_FAIL"
          touch /tmp/egStartupErrorRetrySucceed
          exit 1
        fi

  main:
    lifecycle:
      install:
        all: echo All installed
      run: |-
        echo main of config_install_error is running
        while true; do
        date; sleep 5;
        done
    dependencies:
      - startupErrorRetry