name: Android CI

on:
  push:
    branches:
      - main
      - feature/android2
      - fix/after_v2.5.6_merge
    tags:
      - '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: macos-latest
    name: Android tests
    steps:
      - name: Checkout nucleus
        uses: actions/checkout@v2
        with:
          path: aws-greengrass-nucleus

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Checkstyle validation
        working-directory: ./aws-greengrass-nucleus/android
        run: ./gradlew checkstyle
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: './**/build/reports/checkstyle-report.xml'

      - name: PMD validation
        working-directory: ./aws-greengrass-nucleus/android
        run: ./gradlew pmd
      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: './**/build/reports/pmd-report.xml'

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          crucial_test_classes: "\
            com.aws.greengrass.builtin.services.configstore.ConfigStoreIPCEventStreamAgentTest,\
            com.aws.greengrass.builtin.services.lifecycle.LifecycleIPCEventStreamAgentTest,\
            com.aws.greengrass.builtin.services.mqttproxy.MqttProxyIPCAgentTest,\
            com.aws.greengrass.builtin.services.pubsub.PubSubIPCEventStreamAgentTest,\
            com.aws.greengrass.componentmanager.ComponentManagerTest,\
            com.aws.greengrass.deployment.DeploymentConfigMergerTest,\
            com.aws.greengrass.deployment.DeploymentServiceTest,\
            com.aws.greengrass.deployment.IotJobsHelperTest,\
            com.aws.greengrass.deployment.ShadowDeploymentListenerTest,\
            com.aws.greengrass.ipc.IPCEventStreamServiceTest,\
            com.aws.greengrass.lifecyclemanager.KernelLifecycleTest,\
            com.aws.greengrass.lifecyclemanager.LifecycleTest,\
            com.aws.greengrass.lifecyclemanager.SetupDependencyTest,\
            com.aws.greengrass.mqttclient.AwsIotMqttClientTest,\
            com.aws.greengrass.tes.HttpServerImplTest,\
            com.aws.greengrass.tes.TokenExchangeServiceTest,\
            com.aws.greengrass.tes.CredentialRequestHandlerTest,\
            com.aws.greengrass.tes.IotCloudHelperTest,\
            com.aws.greengrass.android.provision.BaseProvisionManagerTest,\
            com.aws.greengrass.lifecyclemanager.AndroidRunnerTest,\
            com.aws.greengrass.android.managers.AndroidBaseComponentManagerTest,\
            com.aws.greengrass.android.managers.CmdParserTest,\
            com.aws.greengrass.util.platforms.android.AndroidVirtualCmdExecTest,\
            com.aws.greengrass.util.platforms.android.AndroidShellExecTest,\
            com.aws.greengrass.android.managers.AndroidBaseComponentControlTest,\
            com.aws.greengrass.android.managers.AndroidBaseApkManagerTest\
            "
        with:
          api-level: 31
          arch: x86_64
          emulator-build: 8143646
          working-directory: ./aws-greengrass-nucleus/android
          script: ./gradlew -b ./greengrass-nucleus-android/build.gradle createDebugCoverageReport -Pandroid.testInstrumentationRunnerArguments.class=${{ env.crucial_test_classes }}

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation-test-results
          path: ./**/build/reports/androidTests/connected/*

      - name: Upload coverage results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results
          path: ./**/build/reports/coverage/androidTest/debug/*
