name: checkstyle
on:
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validation
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Init submodules
        env:
          SSHK: ${{ secrets.SUBMODULES_SSHKEY }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSHK" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule update --init --recursive

      - uses: wagoid/commitlint-github-action@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: rm -rf /tmp/*
        continue-on-error: true

      - name: Run checks without tests
        env:
          AWS_REGION: us-west-2
        run: |
          sudo -E mvn -ntp -U test -Dtest=!* -DfailIfNoTests=false

      - name: Run checks on android sources
        run: |
          cp -R android/app/src/main/java src/main/java/xxx
          cp -R android/greengrass-nucleus-android/src/main/java src/main/java/yyy
          cp -R android/greengrass-android-component-base/component-library/src/main/java src/main/java/zzz
          sudo -E mvn clean validate
