name: Code Formatting Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.java'
      - 'pom.xml'
      - 'codestyle/**'

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Check code formatting
      run: mvn spotless:check
