name: Java E2E
on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  e2e-test:
    runs-on: [self-hosted, Linux, greengrass]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Tests
        run: mvn -ntp -U generate-test-sources generate-test-resources test-compile -DskipTests
      - name: Run E2E Tests in parallel
        run: mvn -ntp surefire:test@integration-tests -Dgroups="E2E" -DexcludedGroups="" -Dsurefire.argLine="" -DforkCount=3C -DreuseForks=false
      - name: Run intrusive E2E Tests serially
        run: mvn -ntp surefire:test@integration-tests -Dgroups="E2E-INTRUSIVE" -DexcludedGroups="" -Dsurefire.argLine=""
      - name: Upload Failed Test Report
        uses: actions/upload-artifact@v1.0.0
        if: failure()
        with:
          name: Failed E2E Report
          path: target/surefire-reports
