#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn -U -ntp clean verify -f pom2.xml
      - mvn -U -ntp verify -DskipTests=true
      - java -Dggc.archive=./target/aws.greengrass.nucleus.zip
        -Dtags=NucleusSnapshotUat -Dggc.install.root=$CODEBUILD_SRC_DIR -Dggc.log.level=INFO -Daws.region=us-east-1
        -jar uat/target/nucleus-uat-artifact.jar

artifacts:
  files:
    - 'testResults/**/*'
  name: 'NucleusUatLinuxLogs.zip'

reports:
  uat-reports:
    files:
      - "TEST-greengrass-results.xml"
    file-format: "JUNITXML"